"""empty message

Revision ID: 40cc5fdd7b49
Revises: 886dda56c376
Create Date: 2025-01-08 13:11:01.649255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40cc5fdd7b49'
down_revision = '886dda56c376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epp_detections_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=True),
    sa.Column('composite_id', sa.String(length=150), nullable=True),
    sa.Column('assigned_to_name', sa.String(length=100), nullable=True),
    sa.Column('assigned_to_uid', sa.String(length=100), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id_groups', sa.String(length=100), nullable=True),
    sa.Column('groups', sa.String(length=100), nullable=True),
    sa.Column('hostname', sa.String(length=100), nullable=True),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('platform_name', sa.String(length=100), nullable=True),
    sa.Column('product_type_desc', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('filename', sa.String(length=1000), nullable=True),
    sa.Column('filepath', sa.String(length=1000), nullable=True),
    sa.Column('local_prevalence', sa.String(length=100), nullable=True),
    sa.Column('seconds_to_triaged', sa.Integer(), nullable=True),
    sa.Column('seconds_to_resolved', sa.Integer(), nullable=True),
    sa.Column('severity_name', sa.String(length=100), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('tactic', sa.String(length=100), nullable=True),
    sa.Column('tactic_id', sa.String(length=100), nullable=True),
    sa.Column('technique', sa.String(length=100), nullable=True),
    sa.Column('technique_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('epp_detections_table')
    # ### end Alembic commands ###
