"""empty message

Revision ID: 886dda56c376
Revises: 
Create Date: 2025-01-03 11:11:25.184969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886dda56c376'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dspm_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('qtd', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dspm_table')
    # ### end Alembic commands ###
